[package]

description = "An AI for the game of Go"
name = "iomrascalai"
version = "0.2.3"
authors = ["Urban Hafner <contact@urbanhafner.com>",
        "Thomas Poinsot <thomas.poinsot1@gmail.com>",
        "Igor Polyakov <iopguy+iomrasclai@gmail.com>"]
homepage = "https://github.com/ujh/iomrascalai"
repository = "https://github.com/ujh/iomrascalai"
license = "GPL-3.0+"

[dependencies]
enum_primitive  = "*"
getopts         = "*"
num             = "*"
rand            = "*"
regex           = "*"
regex_macros    = "*"
strenum         = "*"
time            = "*"
smallvec        = "*"
quicksort       = "*"
thread-scoped   = "*"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
